# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    loaders:
        default:
            filesystem:
                bundle_resources:
                    enabled: true
    filter_sets:

        # name our filter set "my_crop_filter"
        covers:
            filters:

                # use and setup the "crop" filter
                crop:

                    # set the size of the cropping area
                    size: [ 600, 600 ]

                    # set the starting coordinates of the crop
                    start: [ 0, 0 ]
        home:
            filters:
                fixed:
                    width: 300
                    height: 300
        home_sm:
            filters:
                fixed:
                    width: 336
                    height: 249
