# Documentation on how to configure the bundle can be found at: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"
    loaders:
        default:
            filesystem:
                bundle_resources:
                    enabled: true
    filter_sets:

        # name our filter set "my_crop_filter"
        covers:
            filters:

                # use and setup the "crop" filter
                crop:

                    # set the size of the cropping area
                    size: [ 600, 600 ]

                    # set the starting coordinates of the crop
                    start: [ 0, 0 ]
        latest_products:
            filters:
                fixed:
                    width: 400
                    height: 400
        carousel_products:
            filters:
                fixed:
                    width: 400
                    height: 400
        random_products_maxi:
            filters:
                fixed:
                    width: 600
                    height: 600
        random_products_mini:
            filters:
                fixed:
                    width: 200
                    height: 200
        category_products:
            filters:
                fixed:
                    width: 300
                    height: 300
        categories:
            filters:
                fixed:
                    width: 400
                    height: 400
        same_products:
            filters:
                fixed:
                    width: 400
                    height: 400
        Thumbnail_products_cart:
            filters:
                thumbnail:
                    size: [ 100, 100 ]
                    mode: outbound
